db.url=D:/Work/myproject/Poword/translation/src/main/java/com/poword/resources/db/stardict.db
api.key=sk-510db35550c84650a88db561093df546

rss.url.politics=http://www.people.com.cn/rss/politics.xml
rss.url.society=http://www.people.com.cn/rss/society.xml
rss.url.legal=http://www.people.com.cn/rss/legal.xml
rss.url.world=http://www.people.com.cn/rss/world.xml
rss.url.haixia=http://www.people.com.cn/rss/haixia.xml
rss.url.military=http://www.people.com.cn/rss/military.xml
rss.url.ywkx=http://www.people.com.cn/rss/ywkx.xml



user.focus_area=??,????,????
user.age=28
user.occupation=????
user.education=??
user.style_preference=????

